### ISSUE TITLE
Javascript error in Admin interface running 'SHOW CONTINUOUS QUERIES'

### ISSUE THREAD

**Issue by nathanielc** [influxdb/influxdb-admin#53]
When you run `SHOW CONTINUOUS QUERIES` you get a js error `Uncaught TypeError: Cannot read property 'map' of undefined` admin.js:312 

Looking at the JSON response from the server the queries are returned but js error prevents them from being displayed.

version 0.9.3

**Comment by beckettsean** [comment]
@nathanielc this repo is the admin UI for versions prior to 0.9. For InfluxDB 0.9 admin UI issues, please open them on the influxdb/influxdb repo: https://github.com/influxdb/influxdb/issues/new.

I'm happy to open an issue for you but then you wouldn't automatically be following it. Can you open a new one there?

**Comment by toddboom** [comment]
@nathanielc sorry for the confusion - i should close this repo down. all of the admin stuff lives here now:
https://github.com/influxdb/influxdb/tree/master/shared/admin

**Comment by nathanielc** [comment]
np, opened a new issue. https://github.com/influxdb/influxdb/issues/3820

A nice and big comment in the README of the repo would have sent me to the right place. Thanks.

**Comment by toddboom** [comment]
@nathanielc good call, thanks!

(also, feel free to use your new superpowers to make changes wherever you think it best!)
